### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by Saman-Dev** [pixelomer/AltDeploy#1]
Given error:

Mail has disabled the following plug-ins:
 - AltPlugin
Contact the makers of these plug-ins for versions that are compatible with Mail 11.2.

**Comment by pixelomer** [comment]
What is your macOS version?

**Comment by Saman-Dev** [comment]
macOS High Sierra

**Comment by BerkeAras** [comment]
I have this issue too :(

**Comment by coolcattune** [comment]
same here apple mail plugin issue on high sierra

**Comment by GeoSn0w** [comment]
Same.

**Comment by robin-geary** [comment]
Same OS/Error

**Comment by shurzG** [comment]
missing menu Manage plug-inc,
MacOS High Sierra 13.6

**Comment by pdembowski** [comment]
im also receiving the mail plugin issue running this version of mac os Catalina 10.15.3 Beta (19D49f) 

to be slightly more specific this is the full erro
Could not connect to Mail plug-in. Please make sure the plug-in is installed and Mail is running, then try again.

**Comment by skydog2** [comment]
I'm trying to use it on my high sierra mac the "mail" program has no button to manage plug-ins so basically the whole thing as I can see is useless.

**Comment by pdembowski** [comment]
I’m Catalina I was able to enable the plug in under preferences mange plug in once enabled it starts to go through the cycle then once it’s about 80% complete it gives the cannot connect to the device error

**Comment by robin-geary** [comment]
Upgraded to Mojave and it works perfectly

**Comment by skydog2** [comment]
My computer is a hackintosh with an invidia graphics card it’s staying as is

**Comment by pilflo** [comment]
I had the same problem with High Sierra 10.13.6, the "manage plugin" button was gone and it seemed impossible to bring it back.
I upgraded to Catalina 10.15.2 and the "manage plugin" button is back, I could easily activate the mail plugin and now it works like a charm

**Comment by paganpaymon** [comment]
I'm running a macbook pro from late 2011, I am unable to upgrade past High Seirra. I get the error message from the mail app itself about how the plugin is not compatable with Mail 11.5. I have been trying to figure out what version of "Mail" apple is currently on, but I don't have the slightest clue on what.

**Comment by skydog2** [comment]
I think the “mail” app is linked to the operating system and the version
with high Sierra has no way that I can see to work with the plugins and
like you I’m stuck with high Sierra unless I want to buy another gpu. I
always run the oldest operating system that I can on macs because with each
newer version of OS X Apple puts more draconian crap in it which requires
hackers to figure out ways around the stuff.

**Comment by pixelomer** [comment]
Fixed in 9618992 and 20122d0 for High Sierra

**Comment by vipzen** [comment]
Already updated to latest version but the error persists.

Mojave 10.14.6, Mail 12.4.

![Screen Shot 2020-01-09 at 23 57 26](https://user-images.githubusercontent.com/7483228/72122216-ecf83d00-333b-11ea-8b21-3e5a509e179e.png)

**Comment by skydog2** [comment]
I think Apple is determined to not let us install anything that isn’t
through their store I hear Catalina is going to prevent non signed programs
to be installed at all. I’m going to stick with high Sierra for at least
another 2 years if possible. I’ll never get another iPhone even though I
like them.

**Comment by pixelomer** [comment]
If you are still having issues, make sure you remove and reinstall the plugin from the AltDeploy menu.

**Comment by TheArmKing** [comment]
Nope, doesn't help
![Screen Shot 2020-01-10 at 15 53 56](https://user-images.githubusercontent.com/41083078/72139430-72720080-33c1-11ea-9cce-ff923412fd8d.png)

**Comment by mkblbj** [comment]
same 10.14.6
